Javascript assignment
NikhithaReddy-26/zemoso-training pull request #3
Opened 2023-03-03 09:57 UTC by NikhithaReddy-26

Q1. Write a program to demonstrate how a function can be passed as a parameter to another function.
Q2. An arrow function takes two arguments firstName and lastName and returns a 2 letter string that represents the first letter of both the arguments. For the arguments Roger and Waters, the function returns ‘RW’. Write this function

2023-03-06 06:49 UTC, msaisrinivas requested changes

2023-03-06 06:49 UTC, msaisrinivas commented on code2.js
> +    return `${firstName.charAt(0)}${lastName.charAt(0)}`;
Change the initials into uppercase.

2023-03-06 06:49 UTC, msaisrinivas commented on assignment.cpp
> +#include <iostream>
remove the already pushed file from PR

2023-03-06 07:20 UTC, NikhithaReddy-26 commented on assignment.cpp
> +#include <iostream>
Done

2023-03-07 01:39 UTC, NikhithaReddy-26 commented on code2.js
> +    return `${firstName.charAt(0)}${lastName.charAt(0)}`;
done

2023-03-08 07:38 UTC, msaisrinivas approved these changes

2023-03-09 18:25 UTC, merged